package com.xiaoyuan.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

/**
 * <p>
 * 
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("tl_school_activity")
public class Activity implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer activityId;

    @TableField("school_ID")
    private Integer schoolId;

    private String activityname;

    private String content;

    private Date startTime;

    private Date endTime;

    private Date createTime;

    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_activity.activity_id
     *
     * @param activityId the value for tl_school_activity.activity_id
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_activity.school_ID
     *
     * @return the value of tl_school_activity.school_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_activity.school_ID
     *
     * @param schoolId the value for tl_school_activity.school_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_activity.activityname
     *
     * @return the value of tl_school_activity.activityname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getActivityname() {
        return activityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_activity.activityname
     *
     * @param activityname the value for tl_school_activity.activityname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setActivityname(String activityname) {
        this.activityname = activityname == null ? null : activityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_activity.content
     *
     * @return the value of tl_school_activity.content
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_activity.content
     *
     * @param content the value for tl_school_activity.content
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_activity.start_time
     *
     * @return the value of tl_school_activity.start_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_activity.start_time
     *
     * @param startTime the value for tl_school_activity.start_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_activity.end_time
     *
     * @return the value of tl_school_activity.end_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_activity.end_time
     *
     * @param endTime the value for tl_school_activity.end_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_activity.create_time
     *
     * @return the value of tl_school_activity.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_activity.create_time
     *
     * @param createTime the value for tl_school_activity.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


}
