package com.xiaoyuan.model;

import com.baomidou.mybatisplus.annotation.TableName;
import java.time.LocalDateTime;
import java.sql.Blob;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import org.springframework.stereotype.Repository;

/**
 * <p>
 * 
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("tl_school_announcement")
@Repository
public class Announcement implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer announcementId;

    @TableField("school_ID")
    private Integer schoolId;

    private String title;

    private String subtitle;

    private byte[] picture;

    private String content;

    private Date createTime;

    public Integer getAnnouncementId() {
        return announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_announcement.announcement_id
     *
     * @param announcementId the value for tl_school_announcement.announcement_id
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setAnnouncementId(Integer announcementId) {
        this.announcementId = announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_announcement.school_ID
     *
     * @return the value of tl_school_announcement.school_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_announcement.school_ID
     *
     * @param schoolId the value for tl_school_announcement.school_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_announcement.title
     *
     * @return the value of tl_school_announcement.title
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_announcement.title
     *
     * @param title the value for tl_school_announcement.title
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_announcement.subtitle
     *
     * @return the value of tl_school_announcement.subtitle
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_announcement.subtitle
     *
     * @param subtitle the value for tl_school_announcement.subtitle
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_announcement.content
     *
     * @return the value of tl_school_announcement.content
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_announcement.content
     *
     * @param content the value for tl_school_announcement.content
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_announcement.create_time
     *
     * @return the value of tl_school_announcement.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_announcement.create_time
     *
     * @param createTime the value for tl_school_announcement.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_announcement.pictuer
     *
     * @return the value of tl_school_announcement.pictuer
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public byte[] getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_announcement.pictuer
     *
     * @param picture the value for tl_school_announcement.pictuer
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }


}
