package com.xiaoyuan.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableId;
import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import org.springframework.stereotype.Repository;

/**
 * <p>
 * 
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("tl_school_band")
@Repository
public class Band implements Serializable {

    private static final long serialVersionUID = 1L;

    @TableId("band_ID")
    private Integer bandId;

    @TableField("student_ID")
    private Integer studentId;

    private String studentname;

    private String schoolname;

    private String classname;

    private String parentname;

    private String Status;

    private Date createTime;

    public Integer getBandId() {
        return bandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_band.band_ID
     *
     * @param bandId the value for tl_school_band.band_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setBandId(Integer bandId) {
        this.bandId = bandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_band.student_ID
     *
     * @return the value of tl_school_band.student_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_band.student_ID
     *
     * @param studentId the value for tl_school_band.student_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_band.create_time
     *
     * @return the value of tl_school_band.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_band.create_time
     *
     * @param createTime the value for tl_school_band.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


}
