package com.xiaoyuan.model;

import com.baomidou.mybatisplus.annotation.TableName;
import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.util.Date;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import org.springframework.stereotype.Repository;

/**
 * <p>
 * 
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("tl_school_homework")
@Repository
public class Homework implements Serializable {

    private static final long serialVersionUID = 1L;

    @ApiModelProperty(value = "作业ID", hidden = true)
    private Integer homeworkId;

    @TableField("student_ID")
    @ApiModelProperty(value = "学生ID", hidden = true)
    private Integer studentId;

    @ApiModelProperty(value = "科目", required = false)
    private String subject;

    @ApiModelProperty(value = "内容", required = false)
    private String content;

    @ApiModelProperty(value = "教师姓名", hidden = true)
    private String teachername;


    @TableField("class_id")
    @ApiModelProperty(value = "班级ID", hidden = true)
    private Integer classId;

    @ApiModelProperty(value = "班级名称", required = false)
    private String classname;

    @ApiModelProperty(value = "截止时间", required = false)
    private Date endTime;

    @ApiModelProperty(value = "文件", required = false)
    private String files;

    @ApiModelProperty(value = "创建时间", hidden = true)
    private Date createTime;

    public Integer getHomeworkId() {
        return homeworkId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_homework.homework_id
     *
     * @param homeworkId the value for tl_school_homework.homework_id
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setHomeworkId(Integer homeworkId) {
        this.homeworkId = homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_homework.student_ID
     *
     * @return the value of tl_school_homework.student_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_homework.student_ID
     *
     * @param studentId the value for tl_school_homework.student_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_homework.subject
     *
     * @return the value of tl_school_homework.subject
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_homework.subject
     *
     * @param subject the value for tl_school_homework.subject
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_homework.content
     *
     * @return the value of tl_school_homework.content
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_homework.content
     *
     * @param content the value for tl_school_homework.content
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_homework.teachername
     *
     * @return the value of tl_school_homework.teachername
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getTeachername() {
        return teachername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_homework.teachername
     *
     * @param teachername the value for tl_school_homework.teachername
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setTeachername(String teachername) {
        this.teachername = teachername == null ? null : teachername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_homework.classname
     *
     * @return the value of tl_school_homework.classname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_homework.classname
     *
     * @param classname the value for tl_school_homework.classname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_homework.end_time
     *
     * @return the value of tl_school_homework.end_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_homework.end_time
     *
     * @param endTime the value for tl_school_homework.end_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_homework.files
     *
     * @return the value of tl_school_homework.files
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getFiles() {
        return files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_homework.files
     *
     * @param files the value for tl_school_homework.files
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setFiles(String files) {
        this.files = files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_homework.create_time
     *
     * @return the value of tl_school_homework.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_homework.create_time
     *
     * @param createTime the value for tl_school_homework.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


}
