package com.xiaoyuan.model;

import com.baomidou.mybatisplus.annotation.TableName;
import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

/**
 * <p>
 * 
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("tl_school_order")
public class Order implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer orderId;

    @TableField("student_ID")
    private Integer studentId;

    private String commodityname;

    private Double cost;

    private String payment;

    private Date createTime;

    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_order.order_id
     *
     * @param orderId the value for tl_school_order.order_id
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_order.student_ID
     *
     * @return the value of tl_school_order.student_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_order.student_ID
     *
     * @param studentId the value for tl_school_order.student_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_order.commodityname
     *
     * @return the value of tl_school_order.commodityname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getCommodityname() {
        return commodityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_order.commodityname
     *
     * @param commodityname the value for tl_school_order.commodityname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setCommodityname(String commodityname) {
        this.commodityname = commodityname == null ? null : commodityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_order.cost
     *
     * @return the value of tl_school_order.cost
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_order.cost
     *
     * @param cost the value for tl_school_order.cost
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_order.payment
     *
     * @return the value of tl_school_order.payment
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_order.payment
     *
     * @param payment the value for tl_school_order.payment
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setPayment(String payment) {
        this.payment = payment == null ? null : payment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_order.create_time
     *
     * @return the value of tl_school_order.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_order.create_time
     *
     * @param createTime the value for tl_school_order.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


}
