package com.xiaoyuan.model;

import com.baomidou.mybatisplus.annotation.TableName;
import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

/**
 * <p>
 * 
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("tl_school_parent")
public class Parent implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer parentId;

    @TableField("student_ID")
    private Integer studentId;

    private String parentname;

    private String sex;

    private String profession;

    private String adress;

    private Integer income;

    private Integer age;

    private String taglib;

    private Date createTime;

    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_parent.parent_id
     *
     * @param parentId the value for tl_school_parent.parent_id
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_parent.student_ID
     *
     * @return the value of tl_school_parent.student_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_parent.student_ID
     *
     * @param studentId the value for tl_school_parent.student_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_parent.parentname
     *
     * @return the value of tl_school_parent.parentname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getParentname() {
        return parentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_parent.parentname
     *
     * @param parentname the value for tl_school_parent.parentname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setParentname(String parentname) {
        this.parentname = parentname == null ? null : parentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_parent.sex
     *
     * @return the value of tl_school_parent.sex
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_parent.sex
     *
     * @param sex the value for tl_school_parent.sex
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_parent.profession
     *
     * @return the value of tl_school_parent.profession
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_parent.profession
     *
     * @param profession the value for tl_school_parent.profession
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_parent.income
     *
     * @return the value of tl_school_parent.income
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Integer getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_parent.income
     *
     * @param income the value for tl_school_parent.income
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setIncome(Integer income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_parent.age
     *
     * @return the value of tl_school_parent.age
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_parent.age
     *
     * @param age the value for tl_school_parent.age
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_parent.taglib
     *
     * @return the value of tl_school_parent.taglib
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getTaglib() {
        return taglib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_parent.taglib
     *
     * @param taglib the value for tl_school_parent.taglib
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setTaglib(String taglib) {
        this.taglib = taglib == null ? null : taglib.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_parent.create_time
     *
     * @return the value of tl_school_parent.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_parent.create_time
     *
     * @param createTime the value for tl_school_parent.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_parent.adress
     *
     * @return the value of tl_school_parent.adress
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_parent.adress
     *
     * @param adress the value for tl_school_parent.adress
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }


}
