package com.xiaoyuan.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

/**
 * <p>
 * 
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("tl_school_school")
public class School implements Serializable {

    private static final long serialVersionUID = 1L;

    @TableId("school_ID")
    private Integer schoolId;

    private String schoolname;

    private String adress;

    @TableField("addTime")
    private Date addTime;

    private Date createTime;

    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_school.school_ID
     *
     * @param schoolId the value for tl_school_school.school_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_school.schoolname
     *
     * @return the value of tl_school_school.schoolname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getSchoolname() {
        return schoolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_school.schoolname
     *
     * @param schoolname the value for tl_school_school.schoolname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setSchoolname(String schoolname) {
        this.schoolname = schoolname == null ? null : schoolname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_school.addTime
     *
     * @return the value of tl_school_school.addTime
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getAddtime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_school.addTime
     *
     * @param addtime the value for tl_school_school.addTime
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setAddtime(Date addtime) {
        this.addTime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_school.create_time
     *
     * @return the value of tl_school_school.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_school.create_time
     *
     * @param createTime the value for tl_school_school.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_school.adress
     *
     * @return the value of tl_school_school.adress
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_school.adress
     *
     * @param adress the value for tl_school_school.adress
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }


}
