package com.xiaoyuan.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableId;
import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import org.springframework.stereotype.Repository;

/**
 * <p>
 * 
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("tl_school_staff")
@Repository
public class Staff implements Serializable {

    private static final long serialVersionUID = 1L;

    @TableId("teacher_ID")
    private Integer teacherId;

    @TableField("school_ID")
    private Integer schoolId;

    private String schoolname;

    private Integer userId;

    private Integer teacherMobilephone;

    private String teacherAdress;

    private Date createTime;

    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_staff.teacher_ID
     *
     * @param teacherId the value for tl_school_staff.teacher_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_staff.school_ID
     *
     * @return the value of tl_school_staff.school_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_staff.school_ID
     *
     * @param schoolId the value for tl_school_staff.school_ID
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_staff.schoolname
     *
     * @return the value of tl_school_staff.schoolname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getSchoolname() {
        return schoolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_staff.schoolname
     *
     * @param schoolname the value for tl_school_staff.schoolname
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setSchoolname(String schoolname) {
        this.schoolname = schoolname == null ? null : schoolname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_staff.user_id
     *
     * @return the value of tl_school_staff.user_id
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_staff.user_id
     *
     * @param userId the value for tl_school_staff.user_id
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_staff.teacher_mobilephone
     *
     * @return the value of tl_school_staff.teacher_mobilephone
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Integer getTeacherMobilephone() {
        return teacherMobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_staff.teacher_mobilephone
     *
     * @param teacherMobilephone the value for tl_school_staff.teacher_mobilephone
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setTeacherMobilephone(Integer teacherMobilephone) {
        this.teacherMobilephone = teacherMobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_staff.create_time
     *
     * @return the value of tl_school_staff.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_staff.create_time
     *
     * @param createTime the value for tl_school_staff.create_time
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_school_staff.teacher_adress
     *
     * @return the value of tl_school_staff.teacher_adress
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public String getTeacherAdress() {
        return teacherAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_school_staff.teacher_adress
     *
     * @param teacherAdress the value for tl_school_staff.teacher_adress
     *
     * @mbggenerated Mon Nov 25 17:21:19 CST 2019
     */
    public void setTeacherAdress(String teacherAdress) {
        this.teacherAdress = teacherAdress == null ? null : teacherAdress.trim();
    }


}
