package com.xiaoyuan.service;

import com.xiaoyuan.model.Amusement;
import com.baomidou.mybatisplus.extension.service.IService;

import java.util.List;

/**
 * <p>
 *  服务类
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
public interface IAmusementService extends IService<Amusement> {
    int deleteByPrimaryKey(Integer amusemenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_amusement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(Amusement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_amusement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    Amusement selectByPrimaryKey(Integer amusemenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_amusement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<Amusement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_amusement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(Amusement record);

}
