package com.xiaoyuan.service;

import com.xiaoyuan.model.Announcement;
import com.baomidou.mybatisplus.extension.service.IService;

import java.util.List;

/**
 * <p>
 *  服务类
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
public interface IAnnouncementService extends IService<Announcement> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_announcement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer announcementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_announcement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_announcement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    Announcement selectByPrimaryKey(Integer announcementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_announcement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<Announcement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_announcement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(Announcement record);

}
