package com.xiaoyuan.service;

import com.xiaoyuan.model.Staff;
import com.baomidou.mybatisplus.extension.service.IService;

import java.util.List;

/**
 * <p>
 *  服务类
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
public interface IStaffService extends IService<Staff> {
    int deleteByPrimaryKey(Integer status_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_staff
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_staff
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    Staff selectByPrimaryKey(Integer status_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_staff
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<Staff> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_staff
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(Staff record);

}
