package com.xiaoyuan.service;

import com.xiaoyuan.model.Students;
import com.baomidou.mybatisplus.extension.service.IService;

import java.util.List;

/**
 * <p>
 *  服务类
 * </p>
 *
 * @author jobob
 * @since 2019-11-26
 */
public interface IStudentsService extends IService<Students> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_students
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_students
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_students
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    Students selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_students
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<Students> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_students
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(Students record);

    List<Students> selectStudents();

}
