package com.xiaoyuan.mapper;

import com.xiaoyuan.model.Activity;
import java.util.List;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

public interface ActivityMapper extends BaseMapper<ActivityMapper> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_activity
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_activity
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_activity
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    Activity selectByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_activity
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<Activity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_activity
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(Activity record);
}