package com.xiaoyuan.mapper;

import com.xiaoyuan.model.Advertisement;
import java.util.List;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AdvertisementMapper extends BaseMapper<AdvertisementMapper> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_advertisement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer advertisementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_advertisement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(Advertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_advertisement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    Advertisement selectByPrimaryKey(Integer advertisementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_advertisement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<Advertisement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_advertisement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(Advertisement record);
}
