package com.xiaoyuan.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.xiaoyuan.model.Announcement;
import java.util.List;

public interface AnnouncementMapper extends BaseMapper<AnnouncementMapper> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_announcement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer announcementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_announcement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_announcement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    Announcement selectByPrimaryKey(Integer announcementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_announcement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<Announcement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_announcement
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(Announcement record);
}