package com.xiaoyuan.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.xiaoyuan.model.Attence;
import java.util.List;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AttenceMapper extends BaseMapper<AttenceMapper> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_attence
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer attenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_attence
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(Attence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_attence
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    Attence selectByPrimaryKey(Integer attenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_attence
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<Attence> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_attence
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(Attence record);

    /**
     * 查询班级
     * @return
     */
    List<Attence> selectClassName(Integer schoolID);

    /**
     * 查询学生
     * @return
     */
    List<Attence> selectStudentname(Integer classId);

    /**
     * 查询详情
     * @return
     */
    List<Attence> selectAttence(Integer studentID);

    /**
     * 考勤统计
     * @param studentID
     * @return
     */
    List<Attence> selectAttenceCount(Integer studentID);
}
