package com.xiaoyuan.mapper;

import com.xiaoyuan.model.Band;
import java.util.List;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

public interface BandMapper extends BaseMapper<BandMapper>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_band
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer bandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_band
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(Band record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_band
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    Band selectByPrimaryKey(Integer bandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_band
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<Band> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_band
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(Band record);
}