package com.xiaoyuan.mapper;

import com.xiaoyuan.model.Homework;
import java.util.List;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface HomeworkMapper extends BaseMapper<HomeworkMapper>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_homework
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer homeworkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_homework
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(Homework record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_homework
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    Homework selectByPrimaryKey(Integer homeworkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_homework
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<Homework> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_homework
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(Homework record);
}
