package com.xiaoyuan.mapper;

import com.xiaoyuan.model.HomeworkReturn;
import java.util.List;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;


public interface Homework_returnMapper extends BaseMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_homework_return
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer homeworkReturnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_homework_return
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(HomeworkReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_homework_return
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    HomeworkReturn selectByPrimaryKey(Integer homeworkReturnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_homework_return
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<HomeworkReturn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_homework_return
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(HomeworkReturn record);
}