package com.xiaoyuan.mapper;

import com.xiaoyuan.model.News;
import java.util.List;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

public interface NewsMapper extends BaseMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_news
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_news
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_news
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    News selectByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_news
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<News> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_news
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(News record);
}