package com.xiaoyuan.mapper;

import com.xiaoyuan.model.School;
import java.util.List;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

public interface SchoolMapper extends BaseMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_school
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer schoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_school
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_school
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    School selectByPrimaryKey(Integer schoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_school
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<School> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_school
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(School record);
}