package com.xiaoyuan.mapper;

import com.xiaoyuan.model.Staff;
import java.util.List;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

public interface StaffMapper extends BaseMapper<StaffMapper>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_staff
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int deleteByPrimaryKey(Integer status_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_staff
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int insert(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_staff
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    Staff selectByPrimaryKey(Integer status_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_staff
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    List<Staff> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_school_staff
     *
     * @mbggenerated Mon Nov 25 17:09:46 CST 2019
     */
    int updateByPrimaryKey(Staff record);
}